# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: 'SDA1'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: 'SecurityReporter'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: |
      **/*Tests.csproj
      **/*Test.csproj
    arguments: '--configuration $(buildConfiguration)'
    workingDirectory: 'SecurityReporter'
  displayName: 'dotnet tests'

- task: CmdLine@2
  inputs:
    script: |      
      npm install
      npm install -g @angular/cli
    workingDirectory: '$(Build.SourcesDirectory)/SecurityReporter/angularapp'
  displayName: 'npm install'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true
    workingDirectory: 'SecurityReporter'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/SecurityReporter/angularapp/dist/angularapp'
    Contents: '**'
    TargetFolder: '$(Build.SourcesDirectory)/SecurityReporter/webapi/bin/Release/net7.0/wwwroot'

- task: CmdLine@2
  inputs:
    script: 'ng build'
    workingDirectory: '$(Build.SourcesDirectory)/SecurityReporter/angularapp'
  displayName: 'ng build'   

- task: CmdLine@2
  inputs:
    script: 'npm install cypress --save-dev --force'
    workingDirectory: '$(Build.SourcesDirectory)/SecurityReporter/angularapp_uiTests'
  displayName: 'npm install cypress' 

- task: CmdLine@2
  inputs:
    script: 'npm cypress run --force'
    workingDirectory: '$(Build.SourcesDirectory)/SecurityReporter/angularapp_uiTests/cypress'
  displayName: 'npx cypress run'