# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: 'SDA1'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: 'SecurityReporter'

- task: CmdLine@2
  inputs:
    script: 'npm install'
    workingDirectory: '$(Build.SourcesDirectory)/SecurityReporter/angularapp'
  displayName: 'npm install'

- task: CmdLine@2
  inputs:
    script: 'npm build'
    workingDirectory: '$(Build.SourcesDirectory)/SecurityReporter/angularapp'
  displayName: 'npm build'   

- task: CmdLine@2
  inputs:
    script: 'npm install cypress --save-dev'
    workingDirectory: '$(Build.SourcesDirectory)/SecurityReporter/angularapp_uiTests'
  displayName: 'npm install cypress' 

- task: CmdLine@2
  inputs:
    script: 'npx cypress run'
    workingDirectory: '$(Build.SourcesDirectory)/SecurityReporter/angularapp_uiTests'
  displayName: 'npx cypress run'  